<a href="https://colab.research.google.com/github/rahulrajpr/TensorFlowDeveloperCertifcateTraining/blob/basics/TensorFlow_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [98]:
import tensorflow as tf
print(tf.__version__)

2.9.2


* scalar - a number with direction
* vector is a number with direction
* matrics - two dimensional array
* tensor - ndimentional arrays

**Creating Tensors using tf.constant**

-- for immutable tensors , values cannot be changed/modefied after creation

In [99]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [100]:
scalar.ndim

0

In [101]:
vector = tf.constant([10,7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [102]:
vector.ndim

1

In [103]:
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [104]:
matrix.ndim

2

In [105]:
matrix = tf.constant([[10,7],
                      [7,10]], dtype = tf.float16)
matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.]], dtype=float16)>

In [106]:
tensor = tf.constant([[[10,2],
                       [3,4],
                       [1,0]]])
tensor

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[10,  2],
        [ 3,  4],
        [ 1,  0]]], dtype=int32)>

In [107]:
tensor.ndim

3

In [108]:
# value cannot be changed/assigned for constant tensors

# tensor[0,0,0].assign(7)

**Creating Tensors using tf.variable**

-- for mutable tensors , values can be changed/modefied after creation

In [109]:
tensor2 = tf.Variable([[[10,2],
                       [3,4],
                       [1,0]]])

In [110]:
# assignment/modification is possible in variable tensors
tensor2[0,0,0].assign(7)

<tf.Variable 'UnreadVariable' shape=(1, 3, 2) dtype=int32, numpy=
array([[[7, 2],
        [3, 4],
        [1, 0]]], dtype=int32)>

**Generating the Random Tensors**

In [111]:
# random numbers are picked from the normal distribution

random1 = tf.random.Generator.from_seed(100)
random1 = random1.normal(shape = (3,2))
random1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.90112925, -0.0175216 ],
       [-0.41884932,  0.29532313],
       [ 0.08036723, -1.7199678 ]], dtype=float32)>

In [112]:
# random values are picked from the uniform distribution

random2 = tf.random.Generator.from_seed(10)
random2 = random2.uniform(shape = (3,2))
random2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.93598676, 0.6513264 ],
       [0.31663585, 0.00111556],
       [0.9212191 , 0.3822806 ]], dtype=float32)>

**Shuffle the tensors rows**

In [113]:
tn = tf.Variable([[[10,2],
                  [3,4],
                  [1,0],
                   [5,8]]])
tn

<tf.Variable 'Variable:0' shape=(1, 4, 2) dtype=int32, numpy=
array([[[10,  2],
        [ 3,  4],
        [ 1,  0],
        [ 5,  8]]], dtype=int32)>

In [114]:
tf.random.shuffle(value = tn, seed = 10)

<tf.Tensor: shape=(1, 4, 2), dtype=int32, numpy=
array([[[10,  2],
        [ 3,  4],
        [ 1,  0],
        [ 5,  8]]], dtype=int32)>

**Tensors of ones**

In [115]:
tf.ones(shape = (2,3), dtype = tf.int64)

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 1, 1],
       [1, 1, 1]])>

**Tensors of zeros**

In [116]:
tf.zeros(shape = [5,5], dtype = tf.int64)

<tf.Tensor: shape=(5, 5), dtype=int64, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])>

**Converting the numpy array to Tensor**

Note : Tensors are computationally quicker in a GPU rather than numpy arrays

In [117]:
import numpy as np

In [118]:
array = np.arange(1,25,1)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [119]:
# converting a numpy array to tensor
tf.constant(value = array)

<tf.Tensor: shape=(24,), dtype=int64, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [120]:
# converting a numpy array to a customised shape
tf.constant(value = array,shape = [3,4,2])

<tf.Tensor: shape=(3, 4, 2), dtype=int64, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])>

**Attributes of the tensors**

In [121]:
ten = tf.zeros(shape = [2,3,4,5])
ten

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [122]:
print('shape of the tensor : ',ten.shape)
print('rank or dimension of the tensor : ', ten.ndim)
print('number of elements in the tensor : ', tf.size(tn))
print('number of elements in the tensor (coverted): ', tf.size(tn).numpy())
print('\n')
print('number of element in the first dimension : ', ten.shape[0])
print('number of element in the last dimension : ', ten.shape[-1]) 

shape of the tensor :  (2, 3, 4, 5)
rank or dimension of the tensor :  4
number of elements in the tensor :  tf.Tensor(8, shape=(), dtype=int32)
number of elements in the tensor (coverted):  8


number of element in the first dimension :  2
number of element in the last dimension :  5


**Indexing the tensor**

In [123]:
ten[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [124]:
ten[0,1]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [125]:
ten[0,1,3]

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>

In [126]:
ten[0,1,3,2]

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

**Indexing Tensors**

In [127]:
# getting the firts 2 items in each dimentions
ten[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [128]:
# get the first element from each dimensions except the final one
ten[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [129]:
# create a rank 2 tensor
rank2_ten = tf.zeros(shape = [4,4], dtype = tf.int64)
rank2_ten

<tf.Tensor: shape=(4, 4), dtype=int64, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])>

In [130]:
# get the last item from each row
rank2_ten[:,-1]

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([0, 0, 0, 0])>

In [131]:
# expand the existing tensor (add new dimension at a particular axis)
tf.expand_dims(rank2_ten,axis = -1) # adding a new dimension at the last axis

<tf.Tensor: shape=(4, 4, 1), dtype=int64, numpy=
array([[[0],
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        [0]]])>

In [132]:
tf.expand_dims(rank2_ten,axis = 0) # adding a new dimension at the 0-axis

<tf.Tensor: shape=(1, 4, 4), dtype=int64, numpy=
array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])>

In [133]:
tf.expand_dims(rank2_ten,axis = 1) # adding a new dimension at the 1-axis

<tf.Tensor: shape=(4, 1, 4), dtype=int64, numpy=
array([[[0, 0, 0, 0]],

       [[0, 0, 0, 0]],

       [[0, 0, 0, 0]],

       [[0, 0, 0, 0]]])>

In [134]:
# Another way of adding dimensions at the end of the tensor

rank2_ten[..., tf.newaxis] # '...' represents all the dimensions prior to the new axis addition.

<tf.Tensor: shape=(4, 4, 1), dtype=int64, numpy=
array([[[0],
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        [0]]])>

**Basic Operations in Tensors**

* The Tensrflow way
* The python way

- Addition / Substraction/ Multiplication / Division

Note : **The tensorflow way is faster in terms of the computation efficiecy**

In [135]:
tensor = tf.constant([[2,3],
                      [4,5]])

tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [136]:
tf.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 13],
       [14, 15]], dtype=int32)>

In [137]:
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 13],
       [14, 15]], dtype=int32)>

In [138]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 30],
       [40, 50]], dtype=int32)>

In [139]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 30],
       [40, 50]], dtype=int32)>

In [140]:
tf.subtract(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-8, -7],
       [-6, -5]], dtype=int32)>

In [141]:
tensor -10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-8, -7],
       [-6, -5]], dtype=int32)>

In [142]:
tf.divide(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.2, 0.3],
       [0.4, 0.5]])>

In [143]:
tensor/ 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.2, 0.3],
       [0.4, 0.5]])>

In [144]:
tf.math.floordiv(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]], dtype=int32)>

In [145]:
tensor//10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]], dtype=int32)>

**Transposing the tensors**

tf.transpose() - flip the axis of an existing tensor

In [146]:
a = tf.constant([[2,3],
                 [4,5],
                 [6,7]])

a

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5],
       [6, 7]], dtype=int32)>

In [147]:
tf.transpose(a)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 4, 6],
       [3, 5, 7]], dtype=int32)>

**Reshaping of tensors**

tf.reshape() shuffules the element of the existing tensors to the new shape specified

In [148]:
a.shape

TensorShape([3, 2])

In [149]:
tf.reshape(a, shape = [2,3])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [5, 6, 7]], dtype=int32)>

**Element wise multiplication**

tensors with same shape can be multiplied element wise

In [150]:
print(a)
print(a)
print(a * a)

tf.Tensor(
[[2 3]
 [4 5]
 [6 7]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[2 3]
 [4 5]
 [6 7]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 4  9]
 [16 25]
 [36 49]], shape=(3, 2), dtype=int32)


**Matrix Multiplication (Dot Product)**

- Rules

1. The inner shape of the tensors should match
2. The resulting tensor should be in the shape of the out shape of the tensors

For example if we have two tensors t1 & t2 having shape (a,b) and (c,d) respectively then

for doc-product multiplication

1. b should be equal to c -- > ( b == c)
2. the resulting tensor will have the shape of (a.d)

Ways in which matrix multiplication is possible for tensor are following.

1. "@" - the python way
2. tf.matmul()
3. tf.tensordot()


In [151]:
# lets create two tensors having the shape according to the rule of the tensormultiplication

a = tf.constant([[2,2,5],
                 [1,8,6]])

b = tf.constant([[10,20],
                 [5,5],
                 [9,8]])

a.shape, b.shape  

(TensorShape([2, 3]), TensorShape([3, 2]))

In [152]:
# matrix multiply the python way

a @ b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 75,  90],
       [104, 108]], dtype=int32)>

In [153]:
b @ a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 40, 180, 170],
       [ 15,  50,  55],
       [ 26,  82,  93]], dtype=int32)>

In [154]:
# matrix - multiply the tensorflow way

tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 75,  90],
       [104, 108]], dtype=int32)>

In [155]:
tf.matmul(b,a)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 40, 180, 170],
       [ 15,  50,  55],
       [ 26,  82,  93]], dtype=int32)>

In [156]:
tf.tensordot(a,b, axes =1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 75,  90],
       [104, 108]], dtype=int32)>

In [157]:
tf.tensordot(b,a, axes = 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 40, 180, 170],
       [ 15,  50,  55],
       [ 26,  82,  93]], dtype=int32)>

**Reshaping & Transposing the tensors for multiplication**

In [158]:
# lets create two tensors having the shape not according to the rule of the tensormultiplication

a = tf.constant([[2,2,5],
                 [1,8,6]])

b = tf.constant([[10,20,30],
                 [5,5,8]])

a.shape, b.shape  

(TensorShape([2, 3]), TensorShape([2, 3]))

Transposing for matrix multiplication

In [159]:
print(a,'\n')
print(b,'\n')
print(tf.transpose(b),'\n')
print(a.shape, b.shape,tf.transpose(b).shape,'\n')

# multipliyting the transposed tensor which satisfy the rule of the matrix mutiplictaion

a @ tf.transpose(b)

tf.Tensor(
[[2 2 5]
 [1 8 6]], shape=(2, 3), dtype=int32) 

tf.Tensor(
[[10 20 30]
 [ 5  5  8]], shape=(2, 3), dtype=int32) 

tf.Tensor(
[[10  5]
 [20  5]
 [30  8]], shape=(3, 2), dtype=int32) 

(2, 3) (2, 3) (3, 2) 



<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[210,  60],
       [350,  93]], dtype=int32)>

Reshaping for the matrix multiplication

In [160]:
print(a,'\n')
print(b,'\n')
print(tf.reshape(b, shape = (3,2)),'\n')
print(a.shape, b.shape,tf.reshape(b, shape = (3,2)).shape,'\n')

# multipliyting the reshaped tensor which satisfy the rule of the matrix mutiplictaion

a @ tf.reshape(b, shape = (3,2))

tf.Tensor(
[[2 2 5]
 [1 8 6]], shape=(2, 3), dtype=int32) 

tf.Tensor(
[[10 20 30]
 [ 5  5  8]], shape=(2, 3), dtype=int32) 

tf.Tensor(
[[10 20]
 [30  5]
 [ 5  8]], shape=(3, 2), dtype=int32) 

(2, 3) (2, 3) (3, 2) 



<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[105,  90],
       [280, 108]], dtype=int32)>

Note 1 : Tranposing and reshaping are different operations resulting in differnet results

- Transposing shifts the axis of the tensor(matrix)
- Reshaping shuffle the element to teh new shape in the order of the tensor(metrix)

Note : Generally, while performing the matxis multiplication, the tranpose is used to satisfy the rules of the matrix multiplications for tensorflow operations

**Changing the Datatype in Tensorflow**

The default memory for datatype in tensor flow is 32 bit

There are 16 bit version of the same data can be used as reduced precision for faster calculations and convergence of the models

tf.cast() - hels us to change the datatype in tensor flow


In [161]:
a = tf.constant([2,3,4])
a.dtype

tf.int32

In [162]:
a = tf.constant([2,3,4])
b = tf.cast(a, dtype = tf.int16)
a.dtype,b.dtype

(tf.int32, tf.int16)

In [163]:
a = tf.constant([2,3,4])
b = tf.cast(a, dtype = tf.float32)
a.dtype,b.dtype

(tf.int32, tf.float32)

In [164]:
a = tf.constant([2.5,3.5,4])
b = tf.cast(a, dtype = tf.float16)
a.dtype,b.dtype

(tf.float32, tf.float16)

In [165]:
a = tf.constant([2.5,3.5,4])
b = tf.cast(a, dtype = tf.int16)
print(a.dtype,b.dtype)

b

<dtype: 'float32'> <dtype: 'int16'>


<tf.Tensor: shape=(3,), dtype=int16, numpy=array([2, 3, 4], dtype=int16)>

**Aggregation in tensor flow**

- absolute value - tf.abs()
- find the minimum - tf.reduce_min()
- find the maximum - tf.reduce_max()
- find the sum - tf.reduce_sum()
- find the mean - tf.reduce_mean()
- find the variance - tf.math.reduce_variance() - "Input needs to be in float or complex datatype" - note the usage of the math class
- find the standards devaiation - tf.math.reduce_std() - "Input needs to be in float or complex datatype" - note the usage of the math class

In [166]:
# lets create a random tensor
a = tf.constant(np.random.randint(10, 100, size = 60))
a

<tf.Tensor: shape=(60,), dtype=int64, numpy=
array([44, 59, 68, 82, 75, 97, 44, 81, 47, 39, 95, 63, 43, 81, 72, 58, 47,
       91, 88, 91, 96, 65, 52, 18, 98, 43, 58, 33, 28, 90, 80, 44, 22, 81,
       38, 28, 79, 60, 18, 26, 25, 60, 88, 40, 77, 60, 71, 14, 97, 94, 16,
       45, 97, 98, 62, 20, 26, 25, 71, 65])>

In [167]:
tf.abs(a)

<tf.Tensor: shape=(60,), dtype=int64, numpy=
array([44, 59, 68, 82, 75, 97, 44, 81, 47, 39, 95, 63, 43, 81, 72, 58, 47,
       91, 88, 91, 96, 65, 52, 18, 98, 43, 58, 33, 28, 90, 80, 44, 22, 81,
       38, 28, 79, 60, 18, 26, 25, 60, 88, 40, 77, 60, 71, 14, 97, 94, 16,
       45, 97, 98, 62, 20, 26, 25, 71, 65])>

In [168]:
tf.reduce_min(a).numpy()

14

In [169]:
tf.reduce_max(a)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [170]:
tf.reduce_sum(a)

<tf.Tensor: shape=(), dtype=int64, numpy=3573>

In [171]:
tf.reduce_mean(a)

<tf.Tensor: shape=(), dtype=int64, numpy=59>

In [172]:
tf.math.reduce_variance(tf.cast(a,dtype = tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=668.5>

In [173]:
tf.math.reduce_std(tf.cast(a, dtype = tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=25.86>

**Positional index of minimum and maximum values in tensorflow**

In [174]:
# create a random 
tf.random.set_seed(42)
a = tf.random.uniform(shape = [50])
a

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [175]:
# return the index position of the minimum value in the set
tf.argmin(a)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [176]:
# return the index position of the maximum value in the set
tf.argmax(a)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [177]:
print(a[tf.argmin(a)])
print(a[tf.argmax(a)])

tf.Tensor(0.009463668, shape=(), dtype=float32)
tf.Tensor(0.9671384, shape=(), dtype=float32)


**Squeezing the 1 dimentional levels from Tensors**

In [178]:
# creating a 5 dimentional (5th rank) tensor with 4 1 level dimensions
tf.random.set_seed(42)
a = tf.constant(tf.random.uniform(shape = [50]), shape = [1,1,1,1,50])
a

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [179]:
a.shape, a.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [180]:
# sqeezing the tensor by removing the unnecessary dimensions
b = tf.squeeze(a)
b

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [181]:
b.shape, b.ndim

(TensorShape([50]), 1)

**One Hot Encoding for TensorFlow**

tf.one_hot(), 

indices = tensor, or a list

depth = upto which level we wanted the encoding

In [182]:
l = [0,1,2,3,4]

In [183]:
tf.one_hot(l, depth = len(l))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [184]:
tf.one_hot(l, depth = 3)

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

**Square, Square Root, Log**

In [185]:
a = tf.range(1,10)
a

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [186]:
tf.square(a)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [187]:
# the values has be non-int for the sqrt to work
tf.sqrt(tf.cast(a, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [188]:
# the values has be non-int for the sqrt to work
# note the usage of tf.math for log
tf.math.log(tf.cast(a, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

**Tensors and Numpy Arrays**

In [189]:
# tensor from numpy array
a = tf.constant(np.array([3.2,1,0]))
a

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3.2, 1. , 0. ])>

In [190]:
# converting tensors back to numpy - method 1
np.array(a)

array([3.2, 1. , 0. ])

In [191]:
# converting tensors back to numpy - method 2
a.numpy()

array([3.2, 1. , 0. ])

In [192]:
# check the basic data type of tensors from and numpy and direct tensors

# basic dtype of tensors from numpy array is tf.float64
# basic dtype of tensors direct is tf.float32

a = tf.constant(np.array([2.1,3,4]))
b = tf.constant([2.1,3,4])

a.dtype, b.dtype

(tf.float64, tf.float32)

Go to Runtime > Change Runtime > Change CPU 

In [193]:
tf.config.list_logical_devices()

[LogicalDevice(name='/device:CPU:0', device_type='CPU'),
 LogicalDevice(name='/device:GPU:0', device_type='GPU')]

In [194]:
!nvidia-smi

Thu Jan  5 14:01:18 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   74C    P0    31W /  70W |    314MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------